services:

  dask-scheduler:
    restart: always
    image: ghcr.io/mlinsightlab/mlinsightlab-dask:main
    command: dask-scheduler
    volumes:
      - ${NOTEBOOK_MOUNT}
      - ${DATA_MOUNT}
    networks:
      - network

  dask-worker:
    restart: always
    image: ghcr.io/mlinsightlab/mlinsightlab-dask:main
    depends_on:
      - dask-scheduler
    command: dask-worker ${DASK_SCHEDULER_ADDRESS}
    volumes:
      - ${NOTEBOOK_MOUNT}
      - ${DATA_MOUNT}
    deploy:
      replicas: 4
    networks:
      - network
  
  jupyter:
    restart: always
    image: ghcr.io/mlinsightlab/mlinsightlab-jupyter:main
    depends_on:
      - dask-worker
      - api-hub
    volumes:
      - ${DATA_MOUNT}
      - ${NOTEBOOK_MOUNT}
      - ${JUPYTERHUB_DATABASE_MOUNT}
      - ${JUPYTERHUB_ETC_MOUNT}
      - ${JUPYTERHUB_CRON_MOUNT}
      - ${JUPYTERHUB_HOME_MOUNT}
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - DASK_SCHEDULER_ADDRESS=${DASK_SCHEDULER_ADDRESS}
      - API_URL=${API_URL}
    networks:
      - network

  mlflow:
    restart: always
    image: ghcr.io/mlinsightlab/mlinsightlab-mlflow:main
    volumes:
      - ${MLFLOW_BACKEND_STORAGE}
      - ${MLFLOW_ARTIFACT_STORAGE}
    environment:
      - MLFLOW_BACKEND_STORE_URI=${MLFLOW_BACKEND_STORE_URI}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - MLFLOW_TRACKING_ARTIFACT_STORE=${MLFLOW_TRACKING_ARTIFACT_STORE}
    entrypoint: /bin/sh -c "mlflow server --artifacts-destination ${MLFLOW_TRACKING_ARTIFACT_STORE} --host 0.0.0.0 --port 2244 --gunicorn-opts '-t ${MLFLOW_TIMEOUT_SECONDS}'"
    networks:
      - network

  api-hub:
    restart: always
    image: ghcr.io/mlinsightlab/mlinsightlab-apihub:main
    depends_on:
      - mlflow
    volumes:
      - ${DATA_MOUNT}
      - ${API_HUB_CACHE_MOUNT}
      - ${API_HUB_DB_MOUNT}
      - ${VARIABLE_STORE_MOUNT}
      - ${PREDICTIONS_MOUNT}
    environment:
      - SERVED_MODEL_CACHE_DIR=${API_HUB_SERVED_MODEL_CACHE_DIR}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - ADMIN_USERNAME=${API_HUB_ADMIN_USERNAME}
      - ADMIN_KEY=${API_HUB_ADMIN_KEY}
      - ADMIN_PASSWORD=${API_HUB_ADMIN_PASSWORD}
      - DATA_DIRECTORY=${API_HUB_DATA_DIRECTORY}
      - VARIABLE_STORE_DIRECTORY=${API_HUB_VARIABLE_STORE_DIRECTORY}
      - PREDICTIONS_CACHE_DIR=${API_HUB_PREDICTIONS_DIR}
    networks:
      - network

  mlil-ui:
    restart: always
    image: ghcr.io/mlinsightlab/mlinsightlab-ui:main
    depends_on:
      - mlflow
      - jupyter
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - INACTIVITY_TIMEOUT=${INACTIVITY_TIMEOUT}
      - API_URL=${API_URL}
    command: uvicorn main:app --host 0.0.0.0 --port 1122
    networks:
      - network

  nginx:
    restart: always
    image: ghcr.io/mlinsightlab/mlinsightlab-nginx:main
    depends_on:
      - jupyter
      - mlflow
      - mlil-ui
    volumes:
      - ./certs/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - ./certs/privkey.pem:/etc/nginx/ssl/privkey.pem
    environment:
      - USE_SSL=true
    ports:
      - "80:80"
      - "443:443"
    command: bash /code/setup.sh
    networks:
      - network

volumes:
  mlflow_artifact_storage:
  mlflow_backend_storage:
  model_server_database:
  model_server_cache:
  jupyter_database:
  variable_store:
  jupyter_cron:
  jupyter_home:
  jupyter_etc:
  notebooks:
  data:

networks:
  network:
