services:

  jupyter:
    restart: always
    image: ghcr.io/mlinsightlab/mlinsightlab-jupyter:latest
    depends_on:
      - postgres-jupyter
      - dask-worker
      - api-hub
    volumes:
      - notebooks:/notebooks
      - jupyter_etc:/etc
      - jupyter_cron:/var/spool/cron
      - jupyter_home:/home
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - DASK_SCHEDULER_ADDRESS=${DASK_SCHEDULER_ADDRESS}
      - API_URL=${API_URL}
      - JUPYTER_POSTGRES_USER=${JUPYTER_POSTGRES_USER}
      - JUPYTER_POSTGRES_PASSWORD=${JUPYTER_POSTGRES_PASSWORD}
      - JUPYTER_POSTGRES_DB=${JUPYTER_POSTGRES_DB}
      - JUPYTER_POSTGRES_HOST=${JUPYTER_POSTGRES_HOST}
      - S3_ENDPOINT_URL=${MINIO_URL_EXTERNAL}
      - OLLAMA_HOST=${OLLAMA_HOST}
    command: /bin/sh -c "echo 'Sleeping to allow for other services to start' && sleep 30 && /bin/sh /code/start_jupyter.sh"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
      restart_policy:
        condition: any
    networks:
      - minio_external_network
      - jupyter_network
      - mlflow_network

  api-hub:
    restart: always
    image: ghcr.io/mlinsightlab/mlinsightlab-apihub:latest
    depends_on:
      - postgres-apihub
      - minio-external
      - mlflow
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - ADMIN_USERNAME=${API_HUB_ADMIN_USERNAME}
      - ADMIN_KEY=${API_HUB_ADMIN_KEY}
      - ADMIN_PASSWORD=${API_HUB_ADMIN_PASSWORD}
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER_BACKEND}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD_BACKEND}
      - S3_ENDPOINT_URL=${MINIO_URL_BACKEND}
      - POSTGRES_USER=${API_HUB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${API_HUB_POSTGRES_PASSWORD}
      - POSTGRES_DB=${API_HUB_POSTGRES_DB}
      - POSTGRES_HOST=${API_HUB_POSTGRES_HOST}
      - STORAGE_HOST=${MINIO_URL_EXTERNAL}
      - STORAGE_USERNAME=${MINIO_ROOT_USER_EXTERNAL}
      - STORAGE_PASSWORD=${MINIO_ROOT_PASSWORD_EXTERNAL}
      - MANAGE_STORAGE=${API_HUB_MANAGE_STORAGE}
      - MODEL_NETWORK=${MODEL_NETWORK}
      - DEPLOY_MODE=${API_HUB_DEPLOY_MODE}
      - OLLAMA_HOST=${OLLAMA_HOST}
    command: /bin/sh -c "echo 'Sleeping to allow for other services to start' && sleep 30 && uvicorn main:app --host 0.0.0.0 --port 8000 --root-path /api"
    deploy:
      placement:
        constraints:
          - "node.role == manager"
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
      restart_policy:
        condition: any
    networks:
      - minio_external_network
      - apihub_network
      - jupyter_network
      - model_network

  ollama:
    restart: always
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    networks:
      - jupyter_network
      - apihub_network
      - model_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
      restart_policy:
        condition: any
