version: '3'

services:

  dask-scheduler:
    restart: always
    image: ghcr.io/dask/dask:latest
    container_name: dask-scheduler
    ports:
      - "8786:8786" # Scheduler
      - "8787:8787" # UI
    command: dask-scheduler
    volumes:
      - notebooks:/home
    networks:
      - network

  dask-worker:
    restart: always
    image: ghcr.io/dask/dask:latest
    depends_on:
      - dask-scheduler
    command: dask-worker tcp://dask-scheduler:8786
    deploy:
      replicas: 4
    networks:
      - network

  #spark-master:
    #restart: always
    #image: bitnami/spark@sha256:a5e3feb9397675e9153bdfc748ff3118f333b5b2addf1e7ab19a82128438d4ca
    #container_name: spark-master
    #ports:
      #- "8080:8080"  # Spark UI
      #- "7077:7077"  # Spark Master
    #volumes:
      #- notebooks:/home
    #environment:
      #- SPARK_MODE=master
    #networks:
      #- network

  #spark-worker:
    #restart: always
    #image: bitnami/spark@sha256:a5e3feb9397675e9153bdfc748ff3118f333b5b2addf1e7ab19a82128438d4ca
    #depends_on:
      #- spark-master
    #environment:
      #- SPARK_MODE=worker
      #- SPARK_MASTER_URL=spark://spark-master:7077
    #deploy:
      #replicas: 4
    #networks:
      #- network
  
  jupyter:
    restart: always
    build: ./jupyter
    image: jupyter
    container_name: jupyter
    ports:
      - "8000:8000"
    volumes:
      - notebooks:/home
      - jh_db:/jh_db
    # Uncomment these lines to enable GPU support
    #deploy:
      #resources:
        #reservations:
          #devices:
            #- driver: nvidia
              #count: all
              #capabilities: [gpu]
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:2244
      - DASK_SCHEDULER_ADDRESS=tcp://dask-scheduler:8786
      - JUPYTER_ENV=jupyterlab
    networks:
      - network

  mlflow:
    restart: always
    build: ./mlflow
    image: mlflow
    container_name: mlflow
    ports:
      - "2244:2244"
    volumes:
      - mlflow_backend_storage:/backend_uri
      - mlflow_artifact_storage:/artifact_store
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:////backend_uri/backend_store.sqlite
      - MLFLOW_TRACKING_URI=http://mlflow:2244
      - MLFLOW_TRACKING_ARTIFACT_STORE=file:///artifact_store
    entrypoint: /bin/sh -c "mlflow server --artifacts-destination file:///artifact_store --host 0.0.0.0 --port 2244"
    networks:
      - network

  webapp:
    restart: always
    build: ./webapp
    container_name: webapp
    ports:
      - "80:80"
    networks:
      - network

volumes:
    mlflow_backend_storage:
    mlflow_artifact_storage:
    minio_data:
    notebooks:
    jh_db:

networks:
  network: