version: '3'

services:

  dask-scheduler:
    restart: always
    image: jwrenn4/opendatascienceplatform-dask
    command: dask-scheduler
    volumes:
      - notebooks:/home
    networks:
      - network

  dask-worker:
    restart: always
    image: jwrenn4/opendatascienceplatform-dask
    depends_on:
      - dask-scheduler
    command: dask-worker tcp://dask-scheduler:8786
    volumes:
      - notebooks:/home
    deploy:
      replicas: 4
    networks:
      - network
    #devices:
      #- driver: nvidia
        #count: all
        #capabilities: [gpu]
  
  jupyter:
    restart: always
    image: jwrenn4/opendatascienceplatform-jupyter
    depends_on:
      - dask-worker
    volumes:
      - notebooks:/home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:2244
      - DASK_SCHEDULER_ADDRESS=tcp://dask-scheduler:8786
    networks:
      - network

  mlflow:
    restart: always
    image: jwrenn4/opendatascienceplatform-mlflow
    container_name: mlflow
    volumes:
      - mlflow_backend_storage:/backend_uri
      - mlflow_artifact_storage:/artifact_store
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:////backend_uri/backend_store.sqlite
      - MLFLOW_TRACKING_URI=http://mlflow:2244
      - MLFLOW_TRACKING_ARTIFACT_STORE=file:///artifact_store
    entrypoint: /bin/sh -c "mlflow server --artifacts-destination file:///artifact_store --host 0.0.0.0 --port 2244"
    networks:
      - network

  model-server:
    restart: always
    image: jwrenn4/opendatascienceplatform-model-server
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:2244
    deploy:
      replicas: 2
    networks:
      - network

  nginx:
    restart: always
    image: jwrenn4/opendatascienceplatform-nginx
    depends_on:
      - jupyter
      - mlflow
    ports:
      - "80:80"
    environment:
      - AUTH_USERNAME=odsp
      - AUTH_PASSWORD=odsp
    command: bash /code/setup.sh
    networks:
      - network

volumes:
    mlflow_backend_storage:
    mlflow_artifact_storage:
    notebooks:

networks:
  network:
