services:

  dask-scheduler:
    restart: always
    build: ./dask
    command: dask-scheduler
    volumes:
      - ${NOTEBOOK_MOUNT}
      - ${DATA_MOUNT}
    networks:
      - network

  dask-worker:
    restart: always
    build: ./dask
    depends_on:
      - dask-scheduler
    command: dask-worker ${DASK_SCHEDULER_ADDRESS}
    volumes:
      - ${NOTEBOOK_MOUNT}
      - ${DATA_MOUNT}
    deploy:
      replicas: 4
    networks:
      - network
  
  jupyter:
    restart: always
    build: ./jupyter
    depends_on:
      - dask-worker
      - api-hub
    volumes:
      - ${DATA_MOUNT}
      - ${NOTEBOOK_MOUNT}
      - ${JUPYTERHUB_DATABASE_MOUNT}
      - ${JUPYTERHUB_ETC_MOUNT}
      - ${JUPYTERHUB_CRON_MOUNT}
      - ${JUPYTERHUB_HOME_MOUNT}
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - DASK_SCHEDULER_ADDRESS=${DASK_SCHEDULER_ADDRESS}
      - API_URL=${API_URL}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - network

  mlflow:
    restart: always
    build: ./mlflow
    volumes:
      - ${MLFLOW_BACKEND_STORAGE}
      - ${MLFLOW_ARTIFACT_STORAGE}
    environment:
      - MLFLOW_BACKEND_STORE_URI=${MLFLOW_BACKEND_STORE_URI}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - MLFLOW_TRACKING_ARTIFACT_STORE=${MLFLOW_TRACKING_ARTIFACT_STORE}
    entrypoint: /bin/sh -c "mlflow server --artifacts-destination ${MLFLOW_TRACKING_ARTIFACT_STORE} --host 0.0.0.0 --port 2244 --gunicorn-opts '-t ${MLFLOW_TIMEOUT_SECONDS}'"
    networks:
      - network

  api-hub:
    restart: always
    build: ./api_hub
    depends_on:
      - mlflow
    volumes:
      - ${DATA_MOUNT}
      - ${API_HUB_CACHE_MOUNT}
      - ${API_HUB_DB_MOUNT}
      - ${VARIABLE_STORE_MOUNT}
    environment:
      - SERVED_MODEL_CACHE_DIR=${API_HUB_SERVED_MODEL_CACHE_DIR}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - ADMIN_USERNAME=${API_HUB_ADMIN_USERNAME}
      - ADMIN_KEY=${API_HUB_ADMIN_KEY}
      - ADMIN_PASSWORD=${API_HUB_ADMIN_PASSWORD}
      - DATA_DIRECTORY=${API_HUB_DATA_DIRECTORY}
      - VARIABLE_STORE_DIRECTORY=${API_HUB_VARIABLE_STORE_DIRECTORY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - network

  mlil-ui:
    restart: always
    build: ./mlil_ui
    depends_on:
      - mlflow
      - jupyter
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - API_URL=${API_URL}
    networks:
      - network

  nginx:
    restart: always
    build: ./nginx
    depends_on:
      - jupyter
      - mlflow
      - mlil-ui
    environment:
      - USE_SSL=false
    ports:
      - "80:80"
    command: bash /code/setup.sh
    networks:
      - network

volumes:
  mlflow_artifact_storage:
  mlflow_backend_storage:
  model_server_database:
  model_server_cache:
  jupyter_database:
  variable_store:
  jupyter_cron:
  jupyter_home:
  jupyter_etc:
  notebooks:
  data:

networks:
  network:
